### PR TITLE
add app source to manifest.toml

### PR DESCRIPTION
**Pull request by OniriCorpe**
@ewilly now the ynh bot can autoupdate apps from gitea/forgejo instances, so we can get rid of the github action and put the app source in the manifest ^w^

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by ewilly** [comment]
@OniriCorpe thanks for the contribution
i am not against getting rid of github actions but at this time i really don't know how works the autoupdate without it and didn't find anything in the documentation.
Without understand it, testing if it works and be able to manually trigger an update i prefer to stay on what i understand and manage and so am not ready to merge your PR
 I am open to learn that process if you know it :-)

**Comment by OniriCorpe** [comment]
i understand!

for reference, the docs: https://yunohost.org/fr/packaging_apps_resources#sources
the code: https://github.com/YunoHost/apps/tree/master/tools/autoupdate_app_sources

the autoupdater runs each day on the ynh own infrastructure

**Comment by ewilly** [comment]
humm as you already merge in testing, current github actions does not work anymore so I have to merge it

**Comment by OniriCorpe** [comment]
> humm as you already merge in testing, current github actions does not work anymore so I have to merge it

I’m sorry ^^’

**Pull request merged**
